import os
import re
import json
from pathlib import Path
from typing import Dict, List, Optional

LANGUAGE_PATTERNS = {
    "python": [".py", ".pyw", ".pyx"],
    "javascript": [".js", ".jsx", ".mjs"],
    "typescript": [".ts", ".tsx"],
    "java": [".java"],
    "kotlin": [".kt", ".kts"],
    "go": [".go"],
    "rust": [".rs"],
    "cpp": [".cpp", ".cc", ".cxx", ".hpp"],
    "c": [".c", ".h"],
    "csharp": [".cs"],
    "ruby": [".rb"],
    "php": [".php"],
    "swift": [".swift"],
    "dart": [".dart"],
    "scala": [".scala"],
    "html": [".html", ".htm"],
    "css": [".css", ".scss", ".less"],
    "sql": [".sql"],
    "shell": [".sh", ".bash"],
    "powershell": [".ps1", ".psm1"],
    "yaml": [".yaml", ".yml"],
    "json": [".json"],
    "markdown": [".md"],
    "dockerfile": ["Dockerfile"],
    "makefile": ["Makefile", "makefile"],
}

FRAMEWORK_PATTERNS = {
    "django": ["manage.py", "django"],
    "flask": ["flask"],
    "fastapi": ["fastapi"],
    "react": ["react", "jsx"],
    "vue": ["vue"],
    "angular": ["angular"],
    "express": ["express"],
    "spring": ["spring-boot", "spring"],
    "dotnet": [".csproj", ".sln"],
    "rails": ["rails"],
    "laravel": ["laravel"],
    "nextjs": ["next.config"],
    "flutter": ["pubspec.yaml"],
    "tensorflow": ["tensorflow"],
    "pytorch": ["pytorch"],
    "pandas": ["pandas"],
}

BUILD_FILE_PATTERNS = {
    "pip": ["requirements.txt", "setup.py", "pyproject.toml"],
    "npm": ["package.json", "package-lock.json", "node_modules"],
    "cargo": ["Cargo.toml", "Cargo.lock"],
    "maven": ["pom.xml"],
    "gradle": ["build.gradle", "build.gradle.kts"],
    "go_mod": ["go.mod", "go.sum"],
    "nuget": [".csproj"],
    "cocoapods": ["Podfile"],
}

ARCH_PATTERNS = [
    (r"src/|src\\.*", "Source directory"),
    (r"lib/|lib\\.*", "Library directory"),
    (r"test/|tests/|spec/", "Test directory"),
    (r"docs?/|documentation/", "Documentation"),
    (r"config/|configuration/", "Configuration"),
    (r"api/|routes/|endpoints/", "API layer"),
    (r"migrations?/|alembic/", "Database migrations"),
    (r"static/|assets/|public/", "Static assets"),
    (r"templates?/|views?/", "Templates/views"),
    (r"docker/|\.docker", "Docker"),
    (r"ci/|\.github/", "CI/CD"),
]


class ProjectAnalyzer:
    def __init__(self, project_path=None):
        self.project_path = Path(project_path or os.getcwd()).resolve()

    def analyze(self) -> Dict:
        return {
            "project_type": self._detect_project_type(),
            "languages": self._detect_languages(),
            "frameworks": self._detect_frameworks(),
            "build_systems": self._detect_build_systems(),
            "architecture": self._infer_architecture(),
            "total_files": self._count_files(),
            "test_framework": self._detect_test_framework(),
            "entry_points": self._find_entry_points(),
        }

    def generate_agents_md(self) -> str:
        analysis = self.analyze()
        lines = [
            f"# {self.project_path.name} - Project Analysis",
            "",
            f"Auto-generated by JARVIS Project Analyzer",
            "",
            "## Overview",
            f"- **Project**: {analysis['project_type']}",
            f"- **Languages**: {', '.join(analysis['languages']) or 'Unknown'}",
            f"- **Frameworks**: {', '.join(analysis['frameworks']) or 'None detected'}",
            f"- **Build**: {', '.join(analysis['build_systems']) or 'None detected'}",
            f"- **Total files**: {analysis['total_files']}",
            "",
            "## Architecture",
        ]
        for entry in analysis["architecture"]:
            lines.append(f"- **{entry['label']}**: {entry['path']}")
        lines.extend([
            "",
            "## Environment & Conventions",
            "- **Language**: " + (analysis['languages'][0] if analysis['languages'] else 'unknown'),
            "- **Test framework**: " + (analysis['test_framework'] or 'none'),
            "- **Entry points**: " + ', '.join(analysis['entry_points'][:5]) if analysis['entry_points'] else 'none',
            "",
            "## Instructions",
            "- Follow existing patterns and naming conventions",
            "- Respect the test structure",
            "- Maintain backward compatibility",
        ])
        return "\n".join(lines)

    def _detect_project_type(self) -> str:
        path = self.project_path
        if (path / "requirements.txt").exists() or (path / "setup.py").exists():
            return "Python Project"
        if (path / "package.json").exists():
            return "Node.js Project"
        if (path / "Cargo.toml").exists():
            return "Rust Project"
        if (path / "pom.xml").exists() or (path / "build.gradle").exists():
            return "Java Project"
        if (path / "pubspec.yaml").exists():
            return "Dart/Flutter Project"
        if (path / "go.mod").exists():
            return "Go Project"
        if (path / "Gemfile").exists():
            return "Ruby Project"
        if (path / "composer.json").exists():
            return "PHP Project"
        py_count = len(list(path.rglob("*.py")))
        js_count = len(list(path.rglob("*.js")))
        if py_count > js_count and py_count > 2:
            return "Python Project"
        if js_count > py_count and js_count > 2:
            return "JavaScript Project"
        return "Multi-language Project"

    def _detect_languages(self) -> List[str]:
        extensions = set()
        lang_counts = {}
        for ext, langs in LANGUAGE_PATTERNS.items():
            for lang in langs:
                pattern = f"**/{lang}" if lang.startswith("Dockerfile") or lang.startswith("Makefile") else f"**/*{lang}"
                files = list(self.project_path.rglob(lang if lang.startswith("Docker") or lang.startswith("Makefile") else f"*{lang}"))
                if files:
                    lang_counts[ext] = len(files)
        sorted_langs = sorted(lang_counts.items(), key=lambda x: -x[1])
        return [lang for lang, _ in sorted_langs[:8]]

    def _detect_frameworks(self) -> List[str]:
        found = []
        for framework, patterns in FRAMEWORK_PATTERNS.items():
            for pattern in patterns:
                if pattern.startswith("."):
                    files = list(self.project_path.rglob(f"*{pattern}"))
                    if files:
                        found.append(framework)
                        break
                else:
                    for f in self.project_path.rglob("*"):
                        if f.is_file() and pattern.lower() in f.read_text(4096, errors="ignore").lower()[:4096]:
                            found.append(framework)
                            break
                    if framework in found:
                        break
        return found

    def _detect_build_systems(self) -> List[str]:
        found = []
        for system, patterns in BUILD_FILE_PATTERNS.items():
            for pattern in patterns:
                if (self.project_path / pattern).exists():
                    found.append(system)
                    break
        return found

    def _infer_architecture(self) -> List[Dict]:
        entries = []
        str_path = str(self.project_path)
        for pattern, label in ARCH_PATTERNS:
            matches = list(self.project_path.rglob("*"))
            for m in matches:
                rel = str(m.relative_to(self.project_path)).replace("\\", "/")
                if re.match(pattern, rel, re.IGNORECASE):
                    entries.append({"label": label, "path": "/" + rel.split("/")[0] if "/" in rel else rel})
                    break
        return entries

    def _count_files(self) -> int:
        return sum(1 for _ in self.project_path.rglob("*") if _.is_file())

    def _detect_test_framework(self) -> Optional[str]:
        has_pytest = list(self.project_path.rglob("pytest.ini")) or list(self.project_path.rglob("pyproject.toml"))
        has_jest = list(self.project_path.rglob("jest.config*"))
        has_mocha = list(self.project_path.rglob(".mocharc*"))
        if has_pytest:
            return "pytest"
        if has_jest:
            return "jest"
        if has_mocha:
            return "mocha"
        return None

    def _find_entry_points(self) -> List[str]:
        entries = ["main.py", "index.js", "app.py", "server.py", "cli.py"]
        found = []
        for entry in entries:
            if (self.project_path / entry).exists():
                found.append(entry)
        return found
